logger:
  logLevel: 100
modules:
  enabled:
    - Config
    - Logger
    - Translation
    - Template
    - DB
config:
  Translation:
    fallback: 'ru_RU'
  Template:
    engine: 'Twig'
  DB:
    engine: 'Mysqli'
    user: 'knws'
    host: 'localhost'
    password: 'fVNrJPsKF2UqxvPoqtnG'
    database: 'knws'
    tableprefix: 'pfx_'
  Logger:
    channel: 'Knws'